{
   "owner" : "aguatest",
   "location" : "bin/apps/jbrowse/jbrowseFeatures.pl",
   "executor" : "/usr/bin/perl",
   "installdir" : "/agua/0.6/t/bin/Agua/Common/Package/outputs/private/apps/aguatest/apps",
   "version" : "0.6.0",
   "name" : "jbrowseFeatures",
   "localonly" : "0",
   "description" : "Generate JBrowse features for all chromosomes in parallel",
   "package" : "apps",
   "parameters" : [
      {
         "value" : "hg19",
         "description" : "Reference species build (e.g., hg19, mm9, rn4)",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--build",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "build",
         "param" : "build",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Number of cpus per job",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--cpus",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "cpus",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "value" : "out.bam",
         "description" : "Name of input file. If not defined, the application will process all files in the inputdir.",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--filename",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "filename",
         "param" : "filename",
         "paramFunction" : "if ( hits != null && hits !=  ) { return hits.match(/([^\\\\/]+)$/)[1]; } for ( var i = 0; i < inputs.length; i++) { if ( inputs[i].value.match(/([^/]+.bam)$/) ) { return inputs[i].value.match(/([^/]+.bam)$/)[1]; }}"
      },
      {
         "value" : "bam",
         "description" : "Type of input file (bam or gff)",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--filetype",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "filetype",
         "param" : "filetype",
         "paramFunction" : ""
      },
      {
         "value" : "%project%/%workflow%",
         "description" : "Directory with chromosome subdirs containing input files. JBrowse output files will be printed to subdirs",
         "discretion" : "essential",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--inputdir",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "directory",
         "category" : "inputdir",
         "param" : "inputdir",
         "paramFunction" : "if ( outdir1 != null && outdir1 !=  ) return outdir1; if ( outdir2 != null && outdir2 !=  ) return outdir2;"
      },
      {
         "value" : "",
         "description" : "Location of JBrowse installation (default: JBROWSE key value in default.conf file.)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--jbrowse",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "jbrowse",
         "param" : "jbrowse",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Key for features in JBrowse",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--key",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "key",
         "param" : "key",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Label for experiment (e.g., bowtie)",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--label",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "label",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Maximum number of jobs to be running or queued concurrently (default: 100)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--maxjobs",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "maxjobs",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Length of sleep in seconds between queue polls (default: 5)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--sleep",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "sleep",
         "param" : "sleep",
         "paramFunction" : ""
      },
      {
         "value" : "human",
         "description" : "Reference species (e.g., human, mouse, rat)",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Use this temporary directory to write data on execution host",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--tempdir",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "tempdir",
         "param" : "tempdir",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : " ",
   "url" : "http://www.aguadev.org/confluence/display/howto/Bioapps+API",
   "type" : "view"
}

