{
   "status" : "",
   "submit" : null,
   "ordinal" : null,
   "owner" : "aguatest",
   "locked" : 0,
   "location" : "/agua/0.6/t/bin/Agua/Common/Package/inputs/apps/bin/filters/filterSNP.pl",
   "executor" : "/usr/bin/perl",
   "name" : "filterSNP",
   "duration" : "",
   "description" : "Filter SNPs by quality, coverage, etc.",
   "stopped" : "",
   "parameters" : [
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--chromosome",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "chromosome",
         "param" : "chromosome",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--coverage",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "coverage",
         "param" : "coverage",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--filename",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "file",
         "category" : "filename",
         "param" : "filename",
         "paramFunction" : ""
      },
      {
         "value" : "%project%/%workflow%",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sav extended pileup format file of predicted SNPs and annotation information",
         "discretion" : "essential",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--inputdir",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "directory",
         "category" : "inputdir",
         "param" : "inputdir",
         "paramFunction" : ""
      },
      {
         "value" : "%project%/%workflow%",
         "description" : "Directory with one subdirectory per reference chromosome, each containing an out.sav.flt filterSNP output file",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "output",
         "paramfile" : "",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--quality",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "quality",
         "param" : "quality",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--sense",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "sense",
         "param" : "sense",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      }
   ],
   "notes" : " ",
   "started" : "",
   "type" : "report",
   "queued" : ""
}

