{
   "status" : "",
   "submit" : null,
   "ordinal" : null,
   "owner" : "aguatest",
   "locked" : 0,
   "location" : null,
   "executor" : "",
   "name" : null,
   "duration" : "",
   "description" : "",
   "stopped" : "",
   "parameters" : [
      {
         "value" : "1",
         "description" : "Clean run (remove old splitfile)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--clean",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "flag",
         "category" : "clean",
         "param" : "clean",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Chromosome-specific *bam files containing aligned reads",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "1",
         "argument" : "",
         "format" : "",
         "paramtype" : "output",
         "paramfile" : "",
         "valuetype" : "files",
         "category" : "hits",
         "param" : "hits",
         "paramFunction" : "return outputdir + /chr*/hit.bam;"
      },
      {
         "value" : "",
         "description" : "Solexa FASTQ format sequence file",
         "discretion" : "essential",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--inputfile",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "file",
         "category" : "inputfile",
         "param" : "inputfile",
         "paramFunction" : ""
      },
      {
         "value" : "fastq",
         "description" : "Type of input sequence. Valid inputs: fastq, fasta, export or qseq",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--inputtype",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "inputtype",
         "param" : "inputtype",
         "paramFunction" : ""
      },
      {
         "value" : "myLabel",
         "description" : "Label describing the data or experiment",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--label",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "label",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Paired-end mate file complementary to inputfile (e.g., s_1_2_sequence.fastq)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--matefile",
         "format" : "fastq",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "file",
         "category" : "matefile",
         "param" : "matefile",
         "paramFunction" : ""
      },
      {
         "value" : "%project%/%workflow%",
         "description" : "Print ELAND alignment files to this directory (will create the directory if it does not exist)",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--outputdir",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "directory",
         "category" : "outputdir",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Paired read analysis parameters to pass to pickBestPair. Default: '--circular' (treats all chromosomes as circular).",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--pairparams",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "pairparams",
         "param" : "pairparams",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Quality value of all bases in fasta mode (Default: 30)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--quality",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "quality",
         "param" : "quality",
         "paramFunction" : ""
      },
      {
         "value" : "1000000",
         "description" : "Number of reads per sub-file",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--reads",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "reads",
         "param" : "reads",
         "paramFunction" : ""
      },
      {
         "value" : "%project%/%workflow%",
         "description" : "Directory containing squashed reference genome files",
         "discretion" : "essential",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--referencedir",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "directory",
         "category" : "referencedir",
         "param" : "referencedir",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "Length of read used for ELAND alignment (Default: min. of seedlength and 32)",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--seedlength",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "integer",
         "category" : "seedlength",
         "param" : "seedlength",
         "paramFunction" : ""
      },
      {
         "value" : "human",
         "description" : "Name of species, e.g., human, mouse, rat.",
         "discretion" : "required",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--species",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "string",
         "category" : "species",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "description" : "",
         "discretion" : "optional",
         "params" : "",
         "ordinal" : "0",
         "argument" : "--splitfile",
         "format" : "",
         "paramtype" : "input",
         "paramfile" : "",
         "valuetype" : "file",
         "category" : "splitfile",
         "param" : "splitfile",
         "paramFunction" : ""
      }
   ],
   "notes" : "",
   "started" : "",
   "type" : null,
   "queued" : ""
}

